---
docker_compose_generator_docker_app_directory: docker_apps

# Always appended to .env files, if docker app defines one.
docker_compose_generator_mandatory_env_file_vars: |
  docker_stack_name={{ docker_app }}
  TZ={{ docker_compose_generator_default_time_zone }}
  public_domain_name={{ public_domain_name }}
  local_domain_name={{ local_domain_name }}
  docker_volume_path={{ docker_compose_generator_default_bind_path }}
  local_subnet_range={{ local_subnet_range | default('192.168.0.0/24') }}
  ansible_host={{ ansible_host }}
  {{ zfs_pool_name | default(false) is truthy | ternary("zfs_pool_name=" + zfs_pool_name, '') }}
